### ISSUE TITLE
Sim stop vs raised exception problem

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#1001]
![image](https://user-images.githubusercontent.com/44397098/192298317-eaa04e35-0aa9-45f6-9883-65582ed35d9a.png)

I was testing the micro:bit classroom integration and stopped the sim at what seemed like the same moment it hit a syntax error. It seemed like it stopped but then started scrolling the error. I could not stop the sim at this point as the stop button was disabled.

Eventually when the syntax error stops scrolling the sim does stop. Thats long enough to write most of this bug report and feel very much out of control of the app.

Something unexpected is going on here. Probably not related to micro:bit classroom.

Code:
```
# Add your Python code here. E.g.
from microbit import *


while True:
    display.scroll('Hello, World!')
    display.show(Image.HEART)
    display.scroll(Image.ANGRY)
    sleep(2000)
```

**Comment by microbit-robert** [comment]
I can reproduce this reliably by running the program, while "Hello, World!) is being displayed, edit the program in any way (even removing the offending line), and it's like we rush through the program that was there and hit the error.

**Comment by microbit-matt-hillsdon** [comment]
Raised https://github.com/microbit-foundation/micropython-microbit-v2/issues/134
