### ISSUE TITLE
Escape, Tab to tab out of the editor is broken

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [microbit-foundation/python-editor-v3#1048]
Escape, Tab to tab out of the editor is broken. We suspect the CodeMirror 6 upgrade. As it's otherwise not possible to tab out we should fix this quickly.

**Comment by microbit-robert** [comment]
Following the changes made here -> https://github.com/codemirror/view/commit/741bcd3bd13c2067ff586a59e153719d0926c4e1, `Escape` is handled by our signatureHelp keymap to close signature help, so line 376 is never called, which sets the `lastEscPress` time.

This is the issue that prompted the change for reference -> https://github.com/codemirror/dev/issues/758
