### ISSUE TITLE
String "Code copied, use paste to insert it." missing from Crowdin.

### ISSUE THREAD

**Issue by Fabi135** [microbit-foundation/python-editor-v3#1199]
The string "Code copied, use paste to insert it." is missing from Crowdin. 

https://crowdin.com/editor/microbitorg/all/en-de?view=side-by-side&filter=basic&value=0#q=Code%20copied,%20use%20paste%20to%20insert%20it.

https://github.com/search?q=repo%3Amicrobit-foundation%2Fpython-editor-v3%20%22Code%20copied%2C%20use%20paste%20to%20insert%20it.%22&type=code

Attached is a screenshot of the string: 
![Screenshot 2024-12-14 155304](https://github.com/user-attachments/assets/89c68c79-9611-4552-aee6-d26be75c93c8)

**Comment by microbit-matt-hillsdon** [comment]
Thanks for reporting @Fabi135. We've fixed this in the code and will update it in Crowdin later today.

**Comment by Fabi135** [comment]
@microbit-matt-hillsdon  👍 Thank you
