### ISSUE TITLE
[Serial] Terminal doesn't have a way to zoom the text

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/python-editor-v3#227]
The code editor zoom buttons could be wired to the terminal zoom level. That might be simpler for the UI than having independent controls, but other options can also be considered.

**Comment by microbit-matt-hillsdon** [comment]
This was implemented on #965 (beta only for now). Because of its very constrained space, we've not done the same with the Simulator serial area.

Closing.
