### ISSUE TITLE
[Toolkits] Align dropdown choices with design

### ISSUE THREAD

**Issue by microbit-robert** [microbit-foundation/python-editor-v3#420]
The dropdown choices inside the toolkits that render code examples and snippets need aligning with the new designs. However, the icons used don't currently exist. Needs discussion to resolve.

![image](https://user-images.githubusercontent.com/95928279/149123134-c526d0d9-3851-4c5a-8374-26d88f8ee2c9.png)

**Comment by microbit-matt-hillsdon** [comment]
Agreed to review again after user testing. Not worth doing without image content for the dropdowns.

**Comment by microbit-matt-hillsdon** [comment]
No plans to do this. Closing.
