### ISSUE TITLE
"Confirm replace project" dialog has no headings

### ISSUE THREAD

**Issue by kmcnaught** [microbit-foundation/python-editor-v3#998]
## Bug Description
The dialog you get when opening an example has a `header` but no `h1` / `h2` headings which means a screen reader user can't skip to the title with header navigation. 

![image](https://user-images.githubusercontent.com/12151404/192233720-c484c978-311e-45b6-9e82-d32fe676a152.png)

[edit: confusing typo heading/header]

**Comment by microbit-matt-hillsdon** [comment]
This is likely systemic for dialogs with only one heading and we should look to fix everywhere.
